module.exports = {
  jodDistsSidebar: [
    {
      type: 'link',
      label: '< All JOD Dists',
      href: '/docs/references/jod_dists/',
    },
    {
      type: 'autogenerated', 
      dirName: '.'
    }
  ]
};
