module.exports = {
  jodDistsSidebar: [
    {
      type: 'link',
      label: '< All JSL Services',
      href: '/references/jsl_services/',
    },
    {
      type: 'autogenerated', 
      dirName: '.'
    }
  ]
};
