module.exports = {
  toolsSidebar: [
    {
      type: 'link',
      label: '< Tools',
      href: '/docs/references/tools/',
    },
    {
      type: 'autogenerated', 
      dirName: '.'
    }
  ]
};
